//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolDbMvc.baza_con
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COPI_15_12_16Entities2 : DbContext
    {
        public COPI_15_12_16Entities2()
            : base("name=COPI_15_12_16Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<primerName> primerName { get; set; }
        public DbSet<TBL_ASSESSMENT> TBL_ASSESSMENT { get; set; }
        public DbSet<TBL_CLASS> TBL_CLASS { get; set; }
        public DbSet<TBL_STUDENS> TBL_STUDENS { get; set; }
        public DbSet<TBL_SUBJECT> TBL_SUBJECT { get; set; }
        public DbSet<TBL_TEACHER> TBL_TEACHER { get; set; }
    }
}
