//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolDbMvc.baza_con
{
    using System;
    using System.Collections.Generic;
    
    public partial class primerName
    {
        public string name { get; set; }
        public string surname { get; set; }
        public int id { get; set; }
        public Nullable<int> assessment { get; set; }
        public string classes { get; set; }
        public string theAssessment { get; set; }
    }
}
