//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schoolDbMvc.baza_con
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STUDENS
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> PHONE_NUMBER { get; set; }
        public string CLASS_NAME { get; set; }
        public Nullable<System.DateTime> UDATE { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
    }
}
